### ISSUE TITLE
Add @mepeltier as a maintainer on this project

### ISSUE THREAD

**Issue by dbluhm** [hyperledger/aries-socketdock#8]
I'd like to add Micah Peltier (@mepeltier) as a maintainer on this project.

I feel like I should remember how this works at this point, sorry; @ryjones what's the process to get him added?

Thank you in advance!

**Comment by ryjones** [comment]
@dbluhm [please file an issue here](https://github.com/hyperledger/governance/issues) and create a MAINTAINERS.md for this repo :)
